---
services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566'            # LocalStack Gateway
      - '4510-4559:4510-4559'  # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN             # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack:z'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh:z
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data:z
    restart: always

  # azure-service-bus:
  #   image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
  #   pull_policy: always
  #   volumes:
  #     - "./test-resources/azure-service-bus/config.json:/ServiceBus_Emulator/ConfigFiles/Config.json:z"
  #   ports:
  #     - "5672:5672"
  #     - "5300:5300"
  #   environment:
  #     SQL_SERVER: mssql
  #     MSSQL_SA_PASSWORD: 'Pas_w0rd'
  #     ACCEPT_EULA: "Y"
  #     SQL_WAIT_INTERVAL: 15
  #   depends_on:
  #     - mssql
  #   networks:
  #     cdp-tenant:
  #       aliases:
  #         - "sb-emulator"
  # mssql:
  #   container_name: "mssql"
  #   image: "mcr.microsoft.com/mssql/server:2022-latest"
  #   networks:
  #     cdp-tenant:
  #       aliases:
  #         - "mssql"
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     MSSQL_SA_PASSWORD: 'Pas_w0rd'


  ################################################################################

  # frontend:
  #   image: defradigital/frontend:${FRONTEND_VERSION:-latest}
  #   ports:
  #     - '3000:3000'
  #   links:
  #     - 'localstack:localstack'
  #     - 'redis:redis'
  #   depends_on:
  #     localstack:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   env_file:
  #     - 'compose/aws.env'
  #   environment:
  #     PORT: 3000
  #     NODE_ENV: development
  #     REDIS_HOST: redis
  #     LOCALSTACK_ENDPOINT: http://localstack:4566
  #     USE_SINGLE_INSTANCE_CACHE: true
  #   networks:
  #     - cdp-tenant

  waste-organisation-backend:
    build:
      context: .
      target: development
    ports:
      - '3001:3001'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
      # azure-service-bus:
      #   condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3001
      NODE_ENV: development
      LOCALSTACK_ENDPOINT: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - cdp-tenant
    volumes:
      - ./src:/home/node/src:z
      - ./package.json:/home/node/package.json:z
      - ./package-lock.json:/home/node/package-lock.json:z
      - ./node_modules:/home/node/node_modules:z

################################################################################

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
