---
services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack:z'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh:z
    healthcheck:
      test: ['CMD', 'stat', '/tmp/READY']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data:z
    restart: always

  # azure-service-bus:
  #   image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
  #   pull_policy: always
  #   volumes:
  #     - "./test-resources/azure-service-bus/config.json:/ServiceBus_Emulator/ConfigFiles/Config.json:z"
  #   ports:
  #     - "5672:5672"
  #     - "5300:5300"
  #   environment:
  #     SQL_SERVER: mssql
  #     MSSQL_SA_PASSWORD: 'Pas_w0rd'
  #     ACCEPT_EULA: "Y"
  #     SQL_WAIT_INTERVAL: 15
  #   depends_on:
  #     - mssql
  #   networks:
  #     cdp-tenant:
  #       aliases:
  #         - "sb-emulator"
  # mssql:
  #   container_name: "mssql"
  #   image: "mcr.microsoft.com/mssql/server:2022-latest"
  #   networks:
  #     cdp-tenant:
  #       aliases:
  #         - "mssql"
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     MSSQL_SA_PASSWORD: 'Pas_w0rd'

  ################################################################################

  # frontend:
  #   image: defradigital/frontend:${FRONTEND_VERSION:-latest}
  #   ports:
  #     - '3000:3000'
  #   links:
  #     - 'localstack:localstack'
  #     - 'redis:redis'
  #   depends_on:
  #     localstack:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   env_file:
  #     - 'compose/aws.env'
  #   environment:
  #     PORT: 3000
  #     NODE_ENV: development
  #     REDIS_HOST: redis
  #     LOCALSTACK_ENDPOINT: http://localstack:4566
  #     USE_SINGLE_INSTANCE_CACHE: true
  #   networks:
  #     - cdp-tenant

  waste-movement-backend:
    image: defradigital/waste-movement-backend:latest
    ports:
      - '3002:3001'
    depends_on:
      mongodb:
        condition: service_started
      waste-tracking-id-backend:
        condition: service_started
    environment:
      PORT: 3001
      NODE_ENV: development
      ENVIRONMENT: local
      MONGO_URI: mongodb://mongodb:27017/
      ORG_API_CODES: 'MGUyMWM0NzctODg1My00NTg5LTk5MGMtYWE3ODJiNzQzMWVlPTBlMjFjNDc3LTg4NTMtNDU4OS05OTBjLWFhNzgyYjc0MzFlZQ=='
      MONGO_READ_PREFERENCE: primary
      ACCESS_CRED_WASTE_MOVEMENT_BACKEND: d2FzdGUtbW92ZW1lbnQtYmFja2VuZD05MmZhNjgxZS00NGI0LTRiOWMtOGY3YS01OWMxMTc3NTc0NTI=
      ACCESS_CRED_WASTE_MOVEMENT_EXTERNAL_API: d2FzdGUtbW92ZW1lbnQtZXh0ZXJuYWwtYXBpPTkyZmE2ODFlLTQ0YjQtNGI5Yy04ZjdhLTU5YzExNzc1NzQ1Mg==
      ACCESS_CRED_WASTE_ORGANISATIONS_BACKEND: d2FzdGUtb3JnYW5pc2F0aW9ucy1iYWNrZW5kPTkyZmE2ODFlLTQ0YjQtNGI5Yy04ZjdhLTU5YzExNzc1NzQ1Mg==
      SERVICE_AUTH_PASSWORD: 92fa681e-44b4-4b9c-8f7a-59c117757452
      SERVICE_AUTH_PASSWORD_WASTE_MOVEMENT_BACKEND: 92fa681e-44b4-4b9c-8f7a-59c117757452
      WASTE_TRACKING_SERVICE_URL: http://waste-tracking-id-backend:3001
    networks:
      - cdp-tenant

  waste-tracking-id-backend:
    image: defradigital/waste-tracking-id-backend:latest
    ports:
      - '3003:3001'
    depends_on:
      mongodb:
        condition: service_started
    environment:
      PORT: 3001
      NODE_ENV: development
      ENVIRONMENT: local
      MONGO_URI: mongodb://mongodb:27017/?replicaSet=rs0&directConnection=true
      ACCESS_CRED_WASTE_MOVEMENT_EXTERNAL_API: d2FzdGUtbW92ZW1lbnQtZXh0ZXJuYWwtYXBpPTkyZmE2ODFlLTQ0YjQtNGI5Yy04ZjdhLTU5YzExNzc1NzQ1Mg==
      ACCESS_CRED_WASTE_MOVEMENT_BACKEND: d2FzdGUtbW92ZW1lbnQtYmFja2VuZD05MmZhNjgxZS00NGI0LTRiOWMtOGY3YS01OWMxMTc3NTc0NTI=
    networks:
      - cdp-tenant

  waste-organisation-backend:
    build:
      context: .
      target: development
    ports:
      - '3001:3001'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
      # azure-service-bus:
      #   condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3001
      NODE_ENV: development
      S3_ENDPOINT: http://localstack:4566
      SQS_ENDPOINT: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
      AWS_S3_FORCE_PATH_STYLE: true
      SPREADSHEET_SQS_QUEUE: waste-receiver-background-process
      BULK_UPLOAD_ENDPOINT: 'http://waste-movement-backend:3002'
      BULK_UPLOAD_USERNAME: 'waste-organisations-backend'
      BULK_UPLOAD_PASSWORD: '92fa681e-44b4-4b9c-8f7a-59c117757452'
    networks:
      - cdp-tenant
    volumes:
      - ./src:/home/node/src:z
      - ./package.json:/home/node/package.json:z
      - ./package-lock.json:/home/node/package-lock.json:z
      - ./node_modules:/home/node/node_modules:z

################################################################################

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
